---

- name: Playbook for all hosts
  hosts: all
  become: true
  tasks:

    - name: install apache
      package:
        name: "{{apache_package}}"
        state: latest
        update_cache: yes

- name: Playbook for webservers
  hosts: webservers
  become: true
  tasks:

    - name: ensure Apache is running
      service: 
        name: apache2
        state: started

    - name: delete default index.html
      file:
        path: /var/www/html/index.html
        state: absent

    - name: install git package
      apt:
        name: git
        state: present

    - name: clone git repo 
      git:
        repo: https://github.com/obong003/assign-2-figma.git
        dest: /var/www/html
        force: yes

- name: playbook for dbservers
  hosts: dbservers
  become: true
  tasks:

     - name: ensure Apache is running
       service: 
         name: httpd
         state: started

     - name: delete default index.html
       file:
         path: /var/www/html/index.html
         state: absent

     - name: install git package
       yum:
         name: git
         state: present

     - name: clone git repo
       git:
         repo: https://github.com/obong003/assign-2-figma.git
         dest: /var/www/html
         force: yes
